Feature: Add to Cart functionality


@swaglabs_add_reomve_ToCart

Scenario: VARIFY ADD AND REMOVE ITEM TO THE CART SUCCESSFULLY 
Given OPEN SWAGLABS "<URL>"
Then ENTER valid USER ID PASSWORD AND CLICK SIGN IN
Then Click ON SACUCE LABS BACKPACK 
Then CLICK ON ADD TO CART
Then CLICK ON BACK TO PRODUCTS
Then CLICK ON SAUCE LABS BIKE LIGHT 
Then CLICK ON ADD TO CART AGAIN
Then CLICK ON CART SIGN BY TOP CORNER 
Then CLICK ON REMOVE SAUCE LABS BIKE LIGHT
Then VARIFY ITEM ADDED AND REMOVED TO THE CART SUCCESSFULLY

@swaglabs_checkout_page

Scenario: VARIFY SWAGLABS CHECKOUT HOMEPAGE 

Given OPEN SWAGLABS "<URL>"
Then ENTER valid USER ID PASSWORD AND CLICK SIGN IN
Then Click ON SACUCE LABS BACKPACK 
Then CLICK ON ADD TO CART
Then CLICK ON BACK TO PRODUCTS
Then CLICK ON SAUCE LABS BIKE LIGHT 
Then CLICK ON ADD TO CART AGAIN
Then CLICK ON CART SIGN BY TOP CORNER 
Then CLICK ON REMOVE SAUCE LABS BIKE LIGHT
Then CLICK ON CHECK OUT 
Then FIRST NAME LAST NAME AND ZIP CODE
Then CLICK CONTINUE 
Then CLICK ON FINISH
Then VERIFY THE CHECKOUT HOMEPAGE
